---
collections:
  - community.general
  - ansible.posix
  - freeipa.ansible_freeipa

roles:
  - name: package-downloader
    src: https://github.com/kubealex/role-package-downloader
  - name: host-provisioner
    src: https://github.com/kubealex/role-host-provisioner
  - name: aap2-setup
    src: https://github.com/kubealex/role-aap2-setup
  - name: idm-setup
    src: https://github.com/kubealex/role-idm-setup
  - name: sat-setup
    src: https://github.com/kubealex/role-sat-setup
  - name: sso-setup
    src: https://github.com/kubealex/role-sso-setup
  - name: checksum-helper
    src: https://github.com/kubealex/role-checksum-helper
