---
- name: IDM server configuration playbook
  hosts: idm
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Register system with Red Hat Subscription Manager
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"
        pool_ids: "{{ rhsm_pool_id }}"

    - name: Ensure all packages are updated
      ansible.builtin.dnf:
        name: '*'
        state: latest # noqa package-latest

- name: Playbook to configure IPA servers
  hosts: idm
  become: true
  collections:
    - freeipa.ansible_freeipa

  roles:
  - role: freeipa.ansible_freeipa.ipaserver
    state: present
