---
- name: SSO server configuration playbook
  hosts: sso
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Run SSO setup role
      ansible.builtin.include_role:
        name: sso-setup
