---
- name: Satellite server configuration playbook
  hosts: ipaserver
  become: true
  tasks:
    - name: Run Satellite setup role
      ansible.builtin.include_role:
        name: sat-setup
      vars:
        rhsm_user: "{{ rhsm_user }}"
        rhsm_password: "{{ rhsm_password }}"
        rhsm_pool_id: "{{ rhsm_pool_id }}"
