---
- name: Satellite server configuration playbook
  hosts: satellite
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Run Satellite setup role
      ansible.builtin.include_role:
        name: sat-setup
