---
- name: Download AAP2 Package
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Include downloader role
      ansible.builtin.include_role:
        name: package-downloader
      vars:
        rh_product_checksum: "{{ checksum.aap2 }}"
        rh_api_offline_token: "{{ offline_token }}"

- name: Configure RHSM on nodes and download installer
  hosts: controller,hub
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Include setup role
      ansible.builtin.include_role:
        name: aap2-setup
        apply:
          become: true

    - name: Install AAP2 controller
      ansible.builtin.include_role:
        name: aap2-setup
        apply:
          become: true
      vars:
        install_controller: true

    - name: Install AAP2 automation hub
      ansible.builtin.include_role:
        name: aap2-setup
        apply:
          become: true
      vars:
        install_hub: true
