---
- name: Download AAP2 Package
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Include downloader role
      ansible.builtin.include_role:
        name: package-downloader
      vars:
        rh_product_name: "aap2"
        rh_api_offline_token: "{{ offline_token }}"

- name: Configure and install AAP on nodes
  hosts: controller,hub
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Install AAP2
      ansible.builtin.include_role:
        name: aap2-setup
        apply:
          become: true
      vars:
        aap2_setup_controller: true
        aap2_setup_hub: true
        aap2_setup_servicecatalog: false
