packages:
  - python3-lxml
  - python3-netaddr
  - python3-libvirt
  - python3-pip
  - libvirt-devel
  - libvirt
  - qemu-kvm
  - virt-install
  - virt-manager
modules:
  - module: 01_idm_instance
    instance: rhel-idm
    hostname: idm
    version: rhel8
  - module: 02_controller_instance
    instance: controller
    hostname: controller
    version: rhel9
  - module: 02_hub_instance
    instance: automation-hub
    hostname: hub
    version: rhel9
  - module: 03_satellite_instance
    instance: rhel8-satellite
    hostname: satellite
    version: rhel8
  - module: 04_sso_instance
    instance: rhel8-sso
    hostname: sso
    version: rhel8
  - module: 05_rhel_instance
    instance: rhel
    hostname: rhel-server
    version: rhel8

domain: rh-lab.labs
